{% set name = "pytest-subtests" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_subtests-{{ version }}.tar.gz
  sha256: 350c00adc36c3aff676a66135c81aed9e2182e15f6c3ec8721366918bbbf7580

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools-scm >=6.2.3
  run:
    - pytest >=7.4
    - python
    - attrs >=19.2.0

test:
  source_files:
    - tests
  requires:
    - pip
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture
  dev_url: https://github.com/pytest-dev/pytest-subtests
  doc_url: https://github.com/pytest-dev/pytest-subtests#readme

extra:
  recipe-maintainers:
    - nicoddemus