{% set name = "pytest-subtests" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: cb495bde05551b784b8f0b8adfaa27edb4131469a27c339b80fd8d6ba33f887c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm >=6.2.3
    - wheel
  run:
    - python
    - attrs >=19.2.0
    # Package doesn't support pytest >=9
    # This plugin has been integrated directly into pytest ``9.0``, 
    # so the plugin itself will no longer be maintained and the repository will be archived.
    # https://github.com/pytest-dev/pytest-subtests/blob/main/README.rst?plain=1#L27
    - pytest >=7.4,<9

test:
  source_files:
    - tests
  imports:
    - pytest_subtests
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture
  description: unittest subTest() support and subtests fixture
  dev_url: https://github.com/pytest-dev/pytest-subtests
  doc_url: https://github.com/pytest-dev/pytest-subtests#readme

extra:
  recipe-maintainers:
    - nicoddemus