{% set name = "pytest-subtests" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 7154a8665fd528ee70a76d00216a44d139dc3c9c83521a0f779f7b0ad4f800de

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools-scm >=6.2.3
    - wheel
  run:
    - pytest >=7.4
    - python
    - attrs >=19.2.0

test:
  source_files:
    - tests
  imports:
    - pytest_subtests
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture
  description: unittest subTest() support and subtests fixture
  dev_url: https://github.com/pytest-dev/pytest-subtests
  doc_url: https://github.com/pytest-dev/pytest-subtests#readme

extra:
  recipe-maintainers:
    - nicoddemus