{% set name = "pytest-subtests" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f673d8536eb8a153dd9c871b55c06aa3dea55cbdcf3bb3cdd4c4149a4e81606f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools_scm
  run:
    - pytest >=4.4.0
    - python >=3.5

test:
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-subtests
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: unittest subTest() support and subtests fixture

extra:
  recipe-maintainers:
    - nicoddemus
