travis:
  secure:
    BINSTAR_TOKEN: X19R51VaAcApiH/lH4G69e7WSEPaw6R+5iJxB1yHkcPLoTK2/Cp+x5pKdjFCjgWkxE/u0pCQyibDrgL94hYHCXW/h2netaEnxo66F+e1jV5bamW2ZeBSSZckSmJtUhSH9MLGmsEJvl5iDmnmO+HYxsrSz9CLapMiXpegFEigGVSvnVRpmbaZSIlbMtwEj8804xwoK4gIUCeEF0vvlP/pBpCWB0Q1c0BhHfWbiLwheUk45ItSQWl2m150qPQjxYgGiTfRHp1kz+EIs2dwsuxxjflEi5LuoLCFtBqcuSziM23uxstL3KCLx2Pl3/M+GTiyYsinDdeZoqwQ2vl7G5+94t0WdeKzuKaOIOw4PFitQoMrRXakNsljK0PzazVdS6SsVbHrYmpGs+xcH4dwIS3Q8zdx/e4EbSHWhFpN07PuzTJfBq/sIsamwmgXMQePOpRnSuWqAgLwr5vjAEfQWguUhowa/HCk3HfoDwzAsKymK5QMc2OLm/HaqUiOz1M43GbOsrhvemvWwtomuDLHGVoASFTFzkwwDz8Aiorjt0U9UIs6DDs72TlUdj/gQ+VDZwCT6DHbyMKuD6tEj0XR5YiXscPyOcg8HGTpDaMJncCVTcps1j4CUMD0fcywaRQh9eV3SdDfsRRmLO2H2DYfU1zpJ0XVplrGn8QSQ89jCHuj1eU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
